name: Build cfcli
on: [push, pull_request]

jobs:
  cfcli:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure project builds properly
        run: go build main.go
